### PR TITLE
Phase 1a Wrapup

### PR DESCRIPTION
**Pull request by gwenchee**
This PR closes https://github.com/arfc/fhr-benchmark/issues/4. The major differences are described below. 

During the benchmark meeting, it was pointed out that 3 of my cases has a significant deviation from the average by 1000pcm: 
 
image

It was found that the lack of inter assembly coolant surrounding the hexagonal fuel bundle was causing the discrepancy. The fig below on the left is the previous model, and the fig on the right is the new model with inter assembly coolant. 

Screen Shot 2020-11-24 at 5 23 15 PM

In this PR, I updated the geometry for every phase1a case and reran the simulations on BW. I reran the analysis scripts on these new results which resulted in many updates in the analysis output files.

### CODE REVIEW

**Comment by gwenchee** [comment]
@pep8speaks pep8ify

**Comment by gwenchee** [comment]
@pep8speaks pep8ify

**Review by smpark7 — APPROVED** [review]
Looks like you found the bug! Your input files look good and I assume your output files just changed accordingly.

**Comment by gwenchee** [comment]
@smpark7 Yeah it just looks like a lot of files changed because the output files for every case were all updated with the new model

**Comment by gwenchee** [comment]
Great! Thanks @smpark7, merge?

**Pull request merged**
